"""create constraints table

Revision ID: 1e0a494256e0
Revises: 74998b4f2abc
Create Date: 2026-02-18 09:41:35.204622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0a494256e0'
down_revision: Union[str, None] = '74998b4f2abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timetable_id', sa.Uuid(), nullable=False),
    sa.Column('natural_language_text', sa.String(length=1000), nullable=False),
    sa.Column('formal_representation', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_constraints_timetable_id'), ['timetable_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_constraints_timetable_id'))

    op.drop_table('constraints')
    # ### end Alembic commands ###
